# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    desc: "Generate Go code from all proto files recursively"
    cmds:
      - |
        protoc -I . $(find . -name '*.proto') \
          --go_out=./gen/go/ \
          --go_opt=paths=source_relative \
          --go-grpc_out=./gen/go/ \
          --go-grpc_opt=paths=source_relative
